---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Elasticsearch Curator and required dependencies with pip.
  pip: "name={{ item }}"
  with_items:
    - elasticsearch-curator
    - argparse

- name: mkdir /etc/curator
  file: path=/etc/curator state=directory mode=0755 owner=root

- name: template in curator config
  template: src=curator.yml.j2 dest=/etc/curator/curator.yml mode=0644 owner=root group=root backup=yes

- name: template in curator action file
  template: src=action.yml.j2 dest=/etc/curator/action.yml mode=0644 owner=root group=root backup=yes

- name: Configure cron jobs for Elasticsearch Curator.
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default('present') }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
  with_items: "{{ elasticsearch_curator_cron_jobs }}"
  when: elasticsearch_curator_cron_jobs.0.cron_file is undefined and elasticsearch_curator_cron_jobs.0.user is undefined

- name: Configure cron jobs for Elasticsearch Curator - into etc_cron_d.
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    user: "{{ item.user | default('root') }}"
    cron_file: "{{ item.cron_file | default('curator') }}"
    state: "{{ item.state | default('present') }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
  with_items: "{{ elasticsearch_curator_cron_jobs }}"
  when: elasticsearch_curator_cron_jobs.0.cron_file is defined and elasticsearch_curator_cron_jobs.0.user is defined
